# absolute path to images and labels folders
# Images were collected and annotated in CVAT. The annotations were downloaded in a YOLO1.1 format and folders were created
# The images/annotations were split 80/20 for training/validation

# The main path for your images
path: C:/Users/dezmu/OneDrive/YOLO v8 Material Detection Project
train: images/02_train # (relative to the absolute path)
# Validation data set. Want to keep thing simple
val: images/02_validation # (relative to the absolute path)

# identifying all used classes and their corresponding number
nc: 5  # Number of classes

# The names of our object classes
names:
  - Plastic Cup
  - Water Bottle
  - Paper Cup
  - Soda Can
  - Styrofoam Cup

angle: 70
erasing: 0.5
mixup: 0.1


#    - Water Bottle- 1
#    - Plastic Cup- 0
#    - Styrofoam Cup- 4
#    - Paper Cup- 2
#    - Soda Can- 3

# idea for picking the grip strength
# Have the camera